# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "git.aqq.me/go/app"
  version = "1.3.1"

[[constraint]]
  name = "git.aqq.me/go/nanachi"
  version = "1.11.1"

[[constraint]]
  name = "git.aqq.me/go/retrier"
  version = "2.1.0"

[[constraint]]
  name = "github.com/iph0/conf"
  version = "1.2.2"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[constraint]]
  name = "github.com/kak-tus/healthcheck"
  version = "v0.4.0"

[[constraint]]
  name = "github.com/kshvakov/clickhouse"
  version = "1.3.3"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

[prune]
  go-tests = true
  unused-packages = true
